server:
  port: 9192
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:testdb
    username: sa

 




app:
 messages:
   contactSaveSucc: Contact is Saved
   contactSaveFail: Contact is NOT Saved
   contactDelSucc: Contact is Deleted 
   contactDelFail: Contact is NOT Deleted
